-- EcoScan 3.2: model registry and opt-in training samples.
-- Apply with `supabase db push` using an administrator account.

create table if not exists public.ecoscan_model_releases (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('android', 'ios')),
  version text not null,
  bucket_id text not null default 'ecoscan-models',
  object_path text not null,
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  byte_size bigint not null check (byte_size > 0),
  is_active boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  unique (platform, version)
);

alter table public.ecoscan_model_releases enable row level security;
grant select on public.ecoscan_model_releases to authenticated;

drop policy if exists "authenticated users read active EcoScan models" on public.ecoscan_model_releases;
create policy "authenticated users read active EcoScan models"
on public.ecoscan_model_releases
for select
to authenticated
using (is_active = true);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
) values (
  'ecoscan-models',
  'ecoscan-models',
  false,
  314572800,
  array['application/octet-stream', 'application/zip']
)
on conflict (id) do nothing;

drop policy if exists "authenticated users download released EcoScan models" on storage.objects;
create policy "authenticated users download released EcoScan models"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'ecoscan-models'
  and exists (
    select 1
    from public.ecoscan_model_releases release
    where release.bucket_id = storage.objects.bucket_id
      and release.object_path = storage.objects.name
      and release.is_active = true
  )
);

create table if not exists public.ecoscan_training_samples (
  user_id uuid not null references auth.users(id) on delete cascade,
  client_sample_id text not null,
  storage_path text not null,
  source text not null,
  detector text not null,
  detections jsonb not null default '[]'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'trained')),
  verified_label text,
  verified_bin text,
  annotations jsonb not null default '[]'::jsonb,
  user_reported_label text,
  user_reported_bin text,
  report_note text,
  ai_detected boolean,
  original_label text,
  original_confidence double precision check (
    original_confidence is null or original_confidence between 0 and 1
  ),
  consented_at timestamptz not null default now(),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (user_id, client_sample_id)
);

alter table public.ecoscan_training_samples enable row level security;
grant select, insert, update on public.ecoscan_training_samples to authenticated;

drop policy if exists "users read their EcoScan training samples" on public.ecoscan_training_samples;
create policy "users read their EcoScan training samples"
on public.ecoscan_training_samples
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users create their EcoScan training samples" on public.ecoscan_training_samples;
create policy "users create their EcoScan training samples"
on public.ecoscan_training_samples
for insert
to authenticated
with check (
  auth.uid() = user_id
  and status = 'pending'
  and verified_label is null
  and annotations = '[]'::jsonb
);

drop policy if exists "users retry pending EcoScan training samples" on public.ecoscan_training_samples;
create policy "users retry pending EcoScan training samples"
on public.ecoscan_training_samples
for update
to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (
  auth.uid() = user_id
  and status = 'pending'
  and verified_label is null
  and annotations = '[]'::jsonb
);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
) values (
  'ecoscan-training',
  'ecoscan-training',
  false,
  10485760,
  array['image/jpeg']
)
on conflict (id) do nothing;

drop policy if exists "users upload their own EcoScan training images" on storage.objects;
create policy "users upload their own EcoScan training images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'ecoscan-training'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "users replace their own pending training images" on storage.objects;
create policy "users replace their own pending training images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'ecoscan-training'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'ecoscan-training'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "users read their own EcoScan training images" on storage.objects;
create policy "users read their own EcoScan training images"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'ecoscan-training'
  and (storage.foldername(name))[1] = auth.uid()::text
);
